/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { clearAllData, deleteItemFromData, readAllData, writeData } from './utils';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
registerRoute(/.*(?:firebasestorage\.googleapis)\.com.*$/,
   new StaleWhileRevalidate({
    cacheName: 'post-images'
}));

registerRoute(process.env.REACT_APP_FIREBASE_DATABASE_URL + '/posts.json', function(args){
  return fetch(args.event.request)
  .then(function (res) {
    var clonedRes = res.clone();
    clearAllData('posts')
      .then(function () {
        console.log('clonedRes :>> ', clonedRes);
        return clonedRes.json();
      })
      .then(function (data) {
        console.log('data :>> ', data);
        for (var key in data) {
          writeData('posts', data[key])
        }
      });
    return res;
  }).catch(function(err) {
    console.log('err :>> ', err);
  })
});

self.addEventListener('sync', function(event){
  var url = process.env.REACT_APP_FIREBASE_FUNCTION_URL + '/storePostData';
  console.log('[Serice worker] Background syncing...', event);
  if(event.tag === 'snapgram-sync-posts') {
    console.log('[Service worker] Syncing new posts...');
    event.waitUntil(
      readAllData('sync-posts')
        .then(function(data){
          for(var dt of data){
            var postData = new FormData();
            postData.append('id', dt.id);
            postData.append('caption', dt.caption);
            postData.append('username', dt.username);
            postData.append('location', dt.location);
            postData.append('rawLocationLat', dt.rawLocation.lat);
            postData.append('rawLocationLng', dt.rawLocation.lng);
            postData.append('file', dt.picture, dt.id + '.png');
            console.log('postData :>> ', postData);
            fetch(url, {
              method: 'POST',
              body: postData
            }).then(function(res){
              console.log('Send data...', res);
              if(res.ok){
                res.json().then(function(resData){
                  console.log('resData :>> ', resData);
                  deleteItemFromData('sync-posts', resData.id)
                })
              }
            }).catch(function(err){
              console.log('Error ', err);
            })
          }

        })
    );
  }
})

self.addEventListener('notificationclick', function(event){
  var notification = event.notification;
  var action = event.action;

  console.log(notification);
  if(action === 'confirm'){
    console.log('confirm was chosen');
  } else {
    console.log(action);
    event.waitUntil(
      self.clients.matchAll().
        then(function(clis) {
          var client = clis.find(function(c) {
            return c.visibilityState === 'visible';
          });

          if(client) {
            client.navigate(notification.data.url);
            client.focus();
          } else {
            self.clients.openWindow(notification.data.url);
          }
        })
    )
  }
  notification.close();
})

self.addEventListener('notificationclose', function(event){
  console.log('Notification was closed', event);
})

self.addEventListener('push', function(event){
  console.log('Push notification received', event);

  var data = {title: 'New!', content: 'Something new happened', openUrl: '/'};
  if(event.data){
    data = JSON.parse(event.data.text());
  }

  var options = {
    body: data.content,
    icon: process.env.PUBLIC_URL + 'icons/app-icon-96x96.png',
    badge: process.env.PUBLIC_URL + 'icons/app-icon-96x96.png',
    data: {
      url: data.openUrl
    }
  }

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  )
})